invenio_search_ui/bundles.py, invenio_search_ui/static/js/invenio_search_ui/app.js, invenio_search_ui/static/scss/invenio_search_ui/search.scss, invenio_search_ui/templates/invenio_search_ui/search.html, tests/test_invenio_search_ui.py
after https://github.com/inveniosoftware/invenio-search-js/pull/22 is released.
=> global: invenio-search-js adaption

.travis.yml, CHANGES.rst, MANIFEST.in, RELEASE-NOTES.rst, invenio_search_ui/ext.py, invenio_search_ui/translations/fr/LC_MESSAGES/messages.po, invenio_search_ui/version.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> release: v1.0.0a1

invenio_search_ui/version.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> version: post-release bump

invenio_search_ui/bundles.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> bundles: invenio-search-js upgrade

CHANGES.rst, RELEASE-NOTES.rst, invenio_search_ui/version.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> release: v1.0.0a2

invenio_search_ui/bundles.py
=> bundles: latest `invenio-search-js` update

invenio_search_ui/static/templates/invenio_search_ui/marc21/default.html
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> templates: record url on marc21 template

invenio_search_ui/bundles.py
=> bundles: `invenio-search-js` v0.1.5 addition

invenio_search_ui/static/scss/invenio_search_ui/search.scss, invenio_search_ui/static/templates/invenio_search_ui/marc21/default.html
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> templates: fix collapse links

CHANGES.rst, RELEASE-NOTES.rst, invenio_search_ui/version.py
Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
=> release: v1.0.0a3

MANIFEST.in, docs/api.rst, examples/app-recreate.sh, examples/app.py, examples/requirements.txt, invenio_search_ui/config.py, invenio_search_ui/ext.py, invenio_search_ui/views.py, setup.py, tests/conftest.py
* Improves documentation. (addresses #28)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> docs: addition of param and result sections

AUTHORS.rst, setup.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> global: code style and missing author

AUTHORS.rst, examples/app.py, invenio_search_ui/bundles.py, invenio_search_ui/config.py, invenio_search_ui/static/js/invenio_search_ui/app.js, invenio_search_ui/templates/invenio_search_ui/search.html
* adds year of the documents to the aggregations
* adds possibility of filtering a range of years
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>
=> facets: use the years facet and support year-based filtering

.travis.yml, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, tests/test_examples_app.py
* Adds test_examples_app.py. (closes #33)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> tests: addition of test_examples_app.py

MAINTAINERS
=> docs: new maintainer 

.travis.yml, examples/app-setup.sh, invenio_search_ui/bundles.py, setup.py
=> bundles: addition of `cleancssurl` filter

RELEASE-NOTES.rst, invenio_search_ui/version.py
=> release: v1.0.0a6

examples/app-teardown.sh, invenio_search_ui/bundles.py, invenio_search_ui/config.py, tests/test_invenio_search_ui.py
Addresses inveniosoftware/invenio-app-ils#21
=> templates: add range facet

CHANGES.rst, RELEASE-NOTES.rst, invenio_search_ui/bundles.py, invenio_search_ui/version.py
=> release: v1.0.0a7

.editorconfig, .gitignore, .travis.yml, CONTRIBUTING.rst, INSTALL.rst, README.rst, RELEASE-NOTES.rst, docs/Makefile, docs/api.rst, docs/conf.py, docs/configuration.rst, docs/examplesapp.rst, docs/make.bat, docs/usage.rst, examples/app.py, invenio_search_ui/bundles.py, invenio_search_ui/views.py, pytest.ini, requirements-devel.txt, run-tests.sh, setup.cfg, setup.py, tests/conftest.py
closes https://github.com/inveniosoftware/invenio-search-ui/issues/55
=> global: release checklist changes

.travis.yml, docs/conf.py, invenio_search_ui/__init__.py, invenio_search_ui/config.py, invenio_search_ui/static/templates/invenio_search_ui/facets.html, invenio_search_ui/static/templates/invenio_search_ui/range.html, pytest.ini
=> docs: usage documentation

CHANGES.rst, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js, invenio_search_ui/version.py, invenio_search_ui/webpack.py
Depends on https://github.com/inveniosoftware/react-searchkit/pull/142
=> search: configure sort order option

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/326
=> search: removes side padding in search results and facets

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/331
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/330 
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/328
=> Remove sort label

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/358
Depends on https://github.com/inveniosoftware/invenio-app-rdm/pull/372
=> search: adds styling class for search options

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js, invenio_search_ui/views.py, tests/test_rsk_templates.py
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/109
Closes https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/250
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/101
=> global: change according to rsk

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js, invenio_search_ui/webpack.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/515
=> components: make sortOptions available when overriding

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js
Depends on https://github.com/inveniosoftware/react-searchkit/pull/215
=> A11y- Adding aria-label to instance of sort component

invenio_search_ui/searchconfig.py
Co-authored-by: Pablo <pineirin@gmail.com>
=> searchconfig: add search config helpers

babel.ini, invenio_search_ui/translations/messages.pot, setup.cfg
* remove jinja extensions
* adds fuzzy string true
* update .pot
related inveniosoftware/invenio-app-rdm#1664
=> i18n: extarct messages

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js
needs https://github.com/inveniosoftware/react-invenio-forms/pull/141
=> searchapp: reduce whitespace between results and facets on large screens

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/index.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1701
=> components: add multiple option searchbar

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js
=> Pagination: fix mobile pagination

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/InvenioSearchPagination.js, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/index.js
=> Mobile pagination: make search pagination reusable

CHANGES.rst, invenio_search_ui/__init__.py, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js
Make search icon a functional button.
closes: inveniosoftware/invenio-search-ui#152
=> Header Searchbar: allow empty search

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/common/facets.js, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/index.js
* closes: [inveniosoftware/invenio-administration#56](https://github.com/inveniosoftware/invenio-administration/issues/43)
=> Facets: move facets to invenio-search-ui REQUIRES [https://github.com/inveniosoftware/invenio-app-rdm/pull/1863]

.tx/config, invenio_search_ui/assets/semantic-ui/translations/invenio_search_ui/messages/ar/translations.json, invenio_search_ui/assets/semantic-ui/translations/invenio_search_ui/messages/en/translations.json, invenio_search_ui/assets/semantic-ui/translations/invenio_search_ui/messages/pl/translations.json, invenio_search_ui/assets/semantic-ui/translations/invenio_search_ui/messages/sv/translations.json, invenio_search_ui/assets/semantic-ui/translations/invenio_search_ui/package.json, invenio_search_ui/assets/semantic-ui/translations/invenio_search_ui/translations.pot
=> I18n: extract & push strings

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchDropdowns.js
=> Sorting: ensure selected option has same label as in list

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchAppFacets.js, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/common/facets.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2018
=> facets: add missing namespacing

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/common/facets.js
* closes: https://github.com/inveniosoftware/invenio-requests/issues/347
=> assets: Facet component - fix typo in prop name

CHANGES.rst, invenio_search_ui/__init__.py
Please describe briefly your pull request.
**Reminder** …
=> release: v2.7.0

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/180
=> search bar: add aria-label

CHANGES.rst, invenio_search_ui/__init__.py
Please describe briefly your pull request.
**Reminder** …
=> release: v2.8.0

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchDropdowns.js, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchFilters.js
Partially Closes Issue [#1022](https://github.com/inveniosoftware/invenio-communities/issues/1022)
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
=> Ay11 community views

CHANGES.rst, invenio_search_ui/__init__.py
Please describe briefly your pull request.
**Reminder** …
=> release: v2.8.1

CHANGES.rst, invenio_search_ui/__init__.py
Please describe briefly your pull request.
**Reminder** …
=> release: v2.8.2

CHANGES.rst, invenio_search_ui/__init__.py, invenio_search_ui/config.py, invenio_search_ui/ext.py, invenio_search_ui/searchconfig.py, invenio_search_ui/views.py
New configuration parameter to allow overwritting the default `/search` endpoint
=> Add new config parameter for the default search function.

invenio_search_ui/webpack.py
* closes https://github.com/zenodo/rdm-project/issues/657
=> package: bump react-invenio-forms

invenio_search_ui/webpack.py
* closes https://github.com/inveniosoftware/react-searchkit/issues/278
=> dependencies: update axios

.github/workflows/pypi-publish.yml, .github/workflows/tests.yml, CHANGES.rst, invenio_search_ui/__init__.py, setup.cfg
- setup: pin dependencies
- setup: change to reusable workflows
- release: v3.0.1
=> pin dependencies

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder** …
=> i18n: translate ResultOptions Count element

CHANGES.rst, invenio_search_ui/__init__.py, invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js, setup.cfg
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> I18n: Mark Missing Translations Backport

invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/common/facets.js
Clicking the "Clear" (Clear selection) after a facet has been selected does not do anything.
You can confirm this by visiting https://inveniordm.web.cern.ch/search?q=&l=list&p=1&s=10&sort=newest , selecting a facet and then clicking the clear button. ( the same seems to apply to Zenodo)
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-rep …
=> Fix clear facets

CHANGES.rst, invenio_search_ui/__init__.py
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> release:v2.9.0

CHANGES.rst, invenio_search_ui/__init__.py
* Found this https://github.com/inveniosoftware/invenio-app-rdm/pull/2802
Pin upper version of invenio-search-ui, as v2.9.0 introduces a js dependency change not compatible with other module versions ("react-invenio-forms": "^3.0.0" -> "react-invenio-forms": "^4.0.0")
therefore we will bump the patch version.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
=> Release-v2.8.10

.github/workflows/tests.yml
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> fix: add mint branch to tests
