inveniosoftware/invenio-search-ui

- invenio_search_ui/static/templates/invenio_search_ui/marc21/default.html
* FIX Fixes `window.location` when changing url. The issue was due to
`html5mode` option in angular, which changes the behavior of
`window.location`.
> templates: html5 location issue

- invenio_search_ui/config.py
- invenio_search_ui/ext.py
- invenio_search_ui/static/templates/invenio_search_ui/loading.html
- invenio_search_ui/templates/invenio_search_ui/header.html
- invenio_search_ui/templates/invenio_search_ui/search.html
* Moves template names to configuration for easier customization by
instances as well as easier reuse.
* Adds possibility for easier customization of search input
placeholder.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> templates: easier customization

- AUTHORS.rst
- RELEASE-NOTES.rst
- invenio_search_ui/translations/fr/LC_MESSAGES/messages.po
- setup.cfg
- setup.py
* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> global: inveniosoftware.org

- invenio_search_ui/templates/invenio_search_ui/search.html
* Adds the `search_extra_params` template variable to the
`invenio-search-js` initializer.
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
> views: extra params template variable

- docs/customizing.rst
- docs/index.rst
Provides documentation for the first 2 segments of this issue https://github.com/inveniosoftware/invenio-search-ui/issues/79 since having 2 Search Apps in one page is not yet supported by `invenio-search-ui`
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/79
> docs: adds docs for cutomizing search pages

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js
Regarding space between pagination and footer i don't see any problems, at least not with invenioRDM footer.
closes inveniosoftware/invenio-app-rdm#526
*screenshot*
> pagination: align to center

- invenio_search_ui/version.py
- invenio_search_ui/webpack.py
- part of closing https://github.com/inveniosoftware/invenio-app-rdm/issues/956
- js-dependencies: bump axios to 0.21.1
- release: v2.0.3
> webpack: bump axios for security

- CHANGES.rst
- invenio_search_ui/__init__.py
- invenio_search_ui/webpack.py
`react-searchkit` `v2.0.0` introduces a few breaking changes, and we need to bump `invenio-search-ui`.
We need to decide what to do with `Invenio` version before releasing this version, given that the [current version](https://github.com/inveniosoftware/invenio/blob/2ce61fb8e820979264f1ef4131e544870b5ad09b/setup.py#L50) will not install this version.
> release: v2.1.0

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js
- invenio_search_ui/webpack.py
**Needs [react-invenio-forms PR 118](https://github.com/inveniosoftware/react-invenio-forms/pull/118)**
Solves the responsibility issues for the search results page of [#1360](https://github.com/inveniosoftware/invenio-app-rdm/issues/1360). The My Dashboard issue must be solved in `invenio-app-rdm`.
- Changed the column width of the main content to be full grid-width for mobile and tablet.
- Moved the facet filter to a slide-in sidebar triggered by a filter button for mobile and tablet.
- The desktop version remains the same as before.
The sidebar closes when clicking the close-button or by clicking outside the sidebar.
Accessibility was tested with axe DevTools and VoiceOver.
__Filter closed__
__Filter open__
__Filter closed__
__Filter open__
> search app: add responsive layout

- CHANGES.rst
- invenio_search_ui/__init__.py
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js
fix MultipleOptionsSearchBarCmp click option is missing the context
clicking on a option leads to search always on the first possible
option. now the context of the click is given to the handle function,
similar to the click handle function in the MultipleOptionsSearchBar
component. The context (in this function called "result") gives then
the correct destinationURL.
NOTE: bring back the commented default option
> fix MultipleOptionsSearchBarCmp click option is missing the context

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1697
- Adds missing label to sort dropdown on main search results page
> results: add label to sort dropdown

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchAppFacets.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchAppResultsPane.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchBar.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchDropdowns.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchFilters.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/index.js
Will now reduce search app grid columns to 1 and hide the facets column to prevent it from taking up space if there are no facets.
partly closes https://github.com/inveniosoftware/invenio-administration/issues/6
no facets:
facets (should be the same):
> search app: make list full width if no facets available

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js
multipleOptionsSearchBar: add aria-label
This PR endeavors to add an Aria label (with default value of "Search") to the search button, wherever MultipleOptionsSearchBar appears.
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/155
> MultipleOptionsSearchBar: add aria-label

- CHANGES.rst
- invenio_search_ui/__init__.py
- setup.cfg
- tests/conftest.py
- NOTE invenio-i18n, invenio-records have to be released first
> migrate: flask_babelex replaced by invenio_i18n

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/InvenioSearchPagination.js
- invenio_search_ui/searchconfig.py
Closes https://github.com/zenodo/zenodo-rdm/issues/217
Adds `default_max_results` to pagination options in backend, and passes to `<Pagination/>` component.
> search config: add default_max_results

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchDropdowns.js
Closes https://github.com/inveniosoftware/invenio-communities/issues/983
Forces the text and dropdown icon to align by flex, as the text and the icon would stack vertically if the buttons got too squished. Also added `.fluid-mobile` instead of `.fluid-responive` because of the updated layout (see PR https://github.com/inveniosoftware/invenio-communities/pull/990)
> search dropdown: add flex to button content

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/InvenioSearchPagination.js
Closes https://github.com/zenodo/zenodo-rdm/issues/410, closes https://github.com/zenodo/rdm-project/issues/209
Adds the option of showing total search results next to the pagination.
> pagination: Add optional total results

- docs/conf.py
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/InvenioSearchPagination.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/common/facets.js
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/182, closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2256, closes https://github.com/inveniosoftware/invenio-search-ui/issues/181
- Converts all result-numbers to locale
- Sets the aria-label to the responsive sidebar (needs https://github.com/inveniosoftware/react-invenio-forms/pull/208)
- Modifies the elements within the sidebar according to the PR mentioned above
- Improves screen reader navigation by adding `section` to the search results wrapper element
- Better a11y for count-labels
> facets: convert number to locale, a11y improvements

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2368, closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2172
Fixes issues where the button was not triggering search, and having to double click on the search button because of focus event > click event.
> search bar: fix focus vs click bug and inactive button

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/common/facets.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2352
Replaces the id by aria-label in the search facets, so that the label gets disconnected and the aria-label is used instead. This resolves errors related to duplicate ids due to the responsive sidebar.
> facets: replace id with aria label

- CHANGES.rst
- invenio_search_ui/__init__.py
- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js
Close #198
Fix https://github.com/zenodo/rdm-project/issues/634
Previously as soon as you select the search button via tab it would execute the search. Now we only look for onMouseDown.
We cannot use onClick because the button moves as soon as it is focused via mouse down.
The behaviour is now:
* The button will search with a single `click`
* The button will search with `enter` or `spacebar`
* The input will search if the user presses `enter`
https://github.com/inveniosoftware/invenio-search-ui/assets/6676843/961dbcdb-8585-412f-8937-79d6ed9db0c4
> Description: I tab across the interface and use shift tab to go back to the search box. I then select the search button and press enter to search …
> a11y: allow users to tab across the search button (and release: v2.8.6)

- invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/198
Please note that in case the formula doesn't fit into description completely, it doesn't get printed correctly (2d record on the screenshot)
> search results: render Mathjax in the results list and grid

- setup.cfg
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder** …
> i18n: fix Translations Entry Point

- invenio_search_ui/assets/semantic-ui/translations/invenio_search_ui/messages/index.js
A number of languages were deprecated in https://github.com/inveniosoftware/invenio-search-ui/pull/213, but we forgot to remove them from this config.
**Reminder**
1. You license your …
> i18n: remove deprecated language labels
